version: '3.8'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_inventory
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: inventroy-service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql


